---
- hosts: all
  become: yes
  vars:
    app_user: serveurweb
    app_dir: /home/serveurweb/fastapi_app
    git_repo: git@github.com:Daniween/fastAPI_Ansible.git

  tasks:
    - name: S'assurer que le dossier de destination existe
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"

    - name: Cloner le dépôt si absent
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_dir }}"
        version: main
        update: no
        accept_hostkey: yes
      become_user: "{{ app_user }}"

    - name: Faire un git pull
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes
        update: yes
        accept_hostkey: yes
      become_user: "{{ app_user }}"

    - name: Construire et lancer les conteneurs avec Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ app_dir }}"
