---
- hosts: all
  become: true
  vars:
    app_user: serveurweb
    app_dir: /home/serveurweb/fastapi_app
    git_repo: git@github.com:Daniween/fastAPI_Ansible.git

  tasks:
    - name: S'assurer que le dossier de destination existe
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"

    - name: Ajouter github.com aux known_hosts
      known_hosts:
        path: /home/{{ app_user }}/.ssh/known_hosts
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
        state: present
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0644"

    - name: Cloner le dépôt si absent
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_dir }}"
        version: main
        update: no
        accept_hostkey: yes
        key_file: /home/{{ app_user }}/.ssh/id_rsa

    - name: Faire un git pull
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes
        update: yes
        accept_hostkey: yes
        key_file: /home/{{ app_user }}/.ssh/id_rsa

    - name: Donner les droits à l'utilisateur {{ app_user }}
      file:
        path: "{{ app_dir }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        recurse: yes

    - name: Construire et lancer les conteneurs avec Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ app_dir }}"
